import { chromium } from "playwright";
const SP = process.argv[2];
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 }, deviceScaleFactor: 2 });
await ctx.request.post("http://localhost:3000/api/auth/login", { data: { username: "student", password: "Student@123" } });
const pg = await ctx.newPage();
await pg.goto("http://localhost:3000/student/badges");
await pg.waitForSelector('[aria-label="荣誉展示板"]', { timeout: 20000 });
await pg.waitForTimeout(2200);
await pg.screenshot({ path: `${SP}/h13-board.png`, fullPage: true });
await pg.click('button:has-text("徽章图鉴")');
await pg.waitForSelector('[aria-label="徽章图鉴"]');
await pg.waitForTimeout(600);
await pg.screenshot({ path: `${SP}/h13-codex.png` });
await pg.keyboard.press("Escape");
await pg.waitForTimeout(300);
await pg.click('button[aria-label^="查看徽章详情：题海行星"]');
await pg.waitForSelector('[aria-label^="徽章详情"]', { timeout: 5000 }).catch(() => {});
await pg.waitForTimeout(400);
await pg.screenshot({ path: `${SP}/h13-modal-blur.png` });
console.log("3 shots ok");
await b.close();
