import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import ts from "typescript";
import { SAMPLE_PROJECTS, adaptProject, newProject, validProjects, capacityError, PREP_LIMITS, preparePrepSave, samePrepContent } from "./model.ts";

const recoverySource = readFileSync(new URL("./recovery.ts", import.meta.url), "utf8").replace('from "./model"', `from "${new URL("./model.ts", import.meta.url).href}"`);
const recoveryJs = ts.transpileModule(recoverySource, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { hasUnsubmitted, makePrepBackup, validPrepBackup } = await import(`data:text/javascript;base64,${Buffer.from(recoveryJs).toString("base64")}`);

assert.equal(validProjects(SAMPLE_PROJECTS), true);
const before = JSON.stringify(SAMPLE_PROJECTS);
const blank = newProject({ title: "  新研究课  ", grade: "八年级", subject: "信息科技", kind: "研究课", question: "", conditions: "", members: "" });
assert.equal(blank.title, "新研究课");
assert.equal(blank.example, false);
assert.equal(blank.stage, "草稿");
assert.deepEqual(blank.evidence, []);
assert.deepEqual(blank.rows, []);
assert.deepEqual(blank.discussions, []);
assert.equal(validProjects([blank]), true);
const adapted = adaptProject(SAMPLE_PROJECTS[0]);
assert.notEqual(adapted.id, SAMPLE_PROJECTS[0].id);
assert.deepEqual(adapted.source, { id: SAMPLE_PROJECTS[0].id, title: SAMPLE_PROJECTS[0].title, version: SAMPLE_PROJECTS[0].version });
assert.deepEqual(adapted.evidence, []);
assert.deepEqual(adapted.discussions, []);
assert.equal(adapted.members, "");
assert.equal(adapted.example, false);
adapted.rows[0].task = "changed locally";
assert.equal(JSON.stringify(SAMPLE_PROJECTS), before);
assert.equal(validProjects([adapted]), true);
for (const invalid of [null, {}, [null], [{ ...blank, rows: null }], [{ ...blank, discussions: [{ id: "x" }] }], [{ ...blank, evidence: ["fake"] }], [{ ...blank, source: { id: "x" } }], [{ ...blank, kind: "unknown" }], [{ ...blank, art: "../../other" }], [{ ...blank, revisions: [{ at: "wrong" }] }], [blank, blank], [{ ...blank, id: "" }], [{ ...blank, version: -1 }], [{ ...blank, updatedAt: Infinity }], [{ ...blank, title: " " }], [{ ...blank, unknown: "payload" }], [{ ...blank, goal: "x".repeat(12001) }]]) assert.equal(validProjects(invalid), false);
const full = Array.from({ length: PREP_LIMITS.projects }, (_, i) => ({ ...structuredClone(blank), id: `project-${i}` }));
assert.equal(validProjects(full), true);
assert.equal(capacityError(full), null);
const over = [...full, { ...blank, id: "one-too-many" }];
assert.match(capacityError(over), /24/);
assert.equal(validProjects(over), false);
const big = full.map(p => ({ ...p, goal: "文".repeat(12000), question: "文".repeat(12000) }));
assert.match(capacityError(big), /1.5 MB/);
assert.equal(validProjects(big), false);
const row = SAMPLE_PROJECTS[0].rows[0];
const rowsAtLimit = Array.from({ length: PREP_LIMITS.rows }, (_, i) => ({ ...row, id: `row-${i}` }));
assert.equal(validProjects([{ ...blank, rows: rowsAtLimit }]), true);
assert.equal(validProjects([{ ...blank, rows: [...rowsAtLimit, { ...row, id: "extra" }] }]), false);
assert.equal(validProjects([{ ...blank, rows: [row, row] }]), false);
const discussion = SAMPLE_PROJECTS[0].discussions[0];
assert.equal(validProjects([{ ...blank, discussions: [{ ...discussion, replies: Array(PREP_LIMITS.replies).fill("reply") }] }]), true);
assert.equal(validProjects([{ ...blank, discussions: [{ ...discussion, replies: Array(PREP_LIMITS.replies + 1).fill("reply") }] }]), false);
const revision = { version: 1, at: Date.now(), note: "test", goal: "", question: "" };
assert.equal(validProjects([{ ...blank, revisions: Array(PREP_LIMITS.revisions).fill(revision) }]), true);
assert.equal(validProjects([{ ...blank, revisions: Array(PREP_LIMITS.revisions + 1).fill(revision) }]), false);
const longOrigin = { ...blank, title: "长".repeat(180) };
const boundedCopy = adaptProject(longOrigin);
assert.equal(validProjects([boundedCopy]), true);
assert.equal(boundedCopy.source.title, longOrigin.title);
const unchanged = preparePrepSave(SAMPLE_PROJECTS[0], structuredClone(SAMPLE_PROJECTS[0]), "待讨论", 123456);
assert.equal(unchanged.changed, false);
assert.equal(unchanged.project, SAMPLE_PROJECTS[0]);
const stageChange = preparePrepSave(SAMPLE_PROJECTS[0], structuredClone(SAMPLE_PROJECTS[0]), "共同修订", 123456);
assert.equal(stageChange.changed, true);
assert.equal(stageChange.project.version, 4);
assert.equal(stageChange.project.revisions.length, 1);
assert.equal(stageChange.project.stage, "共同修订");
const fullHistory = { ...structuredClone(SAMPLE_PROJECTS[0]), revisions: Array.from({ length: PREP_LIMITS.revisions }, () => ({ ...revision })) };
assert.equal(preparePrepSave(fullHistory, structuredClone(fullHistory)).changed, false);
const modified = { ...structuredClone(fullHistory), goal: "unsaved goal" };
const copyBefore = JSON.stringify(modified);
assert.match(preparePrepSave(fullHistory, modified).error, /40/);
assert.equal(JSON.stringify(modified), copyBefore);
assert.equal(samePrepContent(fullHistory, modified), false);
assert.equal(samePrepContent(fullHistory, { ...fullHistory, version: 999, updatedAt: 1 }), true);
const discussionId = fullHistory.discussions[0].id;
const pending = { comment: "not added", replies: { [discussionId]: "not sent" }, reasons: { [discussionId]: "not handled" } };
assert.equal(hasUnsubmitted({ comment: "", replies: {}, reasons: {} }), false);
assert.equal(hasUnsubmitted(pending), true);
assert.equal(hasUnsubmitted({ comment: "", replies: {}, reasons: { [discussionId]: "reason only" } }), true);
assert.equal(hasUnsubmitted({ comment: "", replies: { [discussionId]: "reply only" }, reasons: {} }), true);
const backup = makePrepBackup(fullHistory, modified, pending);
const restored = JSON.parse(JSON.stringify(backup));
assert.equal(validPrepBackup(restored), true);
assert.deepEqual(restored.unsubmitted, pending);
assert.deepEqual(restored.draft.evidence, modified.evidence);
assert.deepEqual(restored.draft.discussions, modified.discussions);
assert.deepEqual(restored.saved.revisions, fullHistory.revisions);
backup.draft.evidence[0].observation = "backup is isolated";
assert.notEqual(modified.evidence[0].observation, backup.draft.evidence[0].observation);
assert.equal(validPrepBackup({ ...restored, draft: { ...restored.draft, id: "different-project" } }), false);
assert.equal(validPrepBackup({ ...restored, unsubmitted: { ...pending, reasons: { nonexistent: "orphan text" } } }), false);
assert.equal(validPrepBackup({ ...restored, unsubmitted: { ...pending, comment: "x".repeat(2001) } }), false);
const oversized = { ...structuredClone(blank), goal: "文".repeat(12000), question: "文".repeat(12000), conditions: "文".repeat(12000), evidence: Array.from({ length: PREP_LIMITS.evidence }, (_, i) => ({ id: `e-${i}`, observation: "文".repeat(4000), interpretation: "文".repeat(4000), adjustment: "文".repeat(4000), source: "" })) };
assert.equal(validProjects([oversized]), false);
assert.equal(validPrepBackup(makePrepBackup(blank, oversized, { comment: "", replies: {}, reasons: {} })), true);
assert.equal(JSON.stringify(SAMPLE_PROJECTS), before);
console.log("PASS: provenance, empty drafts, hydration/capacity limits, no-op/full-history save, input preservation, complete backup recovery and unsubmitted-text detection");
