import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, join, resolve, sep } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { startIsolatedManorDevServer } from "./manor-v5-helpers.mjs";

const tempDbDir = mkdtempSync(join(tmpdir(), "eduai-manor-v6-"));
let server;
let base;
let cookie;
let probe;
let sequence = 0;
const op = () => `manor-v6-${String(++sequence).padStart(8, "0")}`;
const checks = [];
async function request(path, body, status = 200, session = cookie, extraHeaders = {}) {
  const response = await fetch(`${base}${path}`, {
    method: body === undefined ? "GET" : "POST",
    headers: { ...(session ? { cookie: session } : {}), ...(body !== undefined ? { "content-type": "application/json" } : {}), ...extraHeaders },
    ...(body !== undefined ? { body: JSON.stringify(body) } : {}), signal: AbortSignal.timeout(60_000),
  });
  const text = await response.text();
  assert.equal(response.status, status, `${path}: ${text.slice(0, 500)}`);
  return JSON.parse(text);
}
async function login(username, password) {
  const response = await fetch(`${base}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username, password }) });
  assert.equal(response.status, 200);
  const session = response.headers.get("set-cookie")?.split(";", 1)[0];
  assert.ok(session);
  return session;
}
const bootstrap = () => request("/api/v2/manor/bootstrap");
const evidence = (missionId, answer) => request("/api/v2/manor/evidence", { operationId: op(), missionId, answer });
const taskPath = "/api/v2/manor/task-runs";
const artifactPath = "/api/v2/manor/artifacts";
try {
  server = await startIsolatedManorDevServer({ label: "manor-v6", tempDbDir });
  base = server.base;
  cookie = await login("student", "Student@123");
  const other = await login("student-p", "Student@123");
  const teacher = await login("teacher", "Teacher@123");
  const initial = await bootstrap();
  assert.equal(initial.schemaVersion, "manor.v2");
  assert.equal(initial.plots.length, 24);
  assert.deepEqual(initial.taskRuns, []);
  assert.equal(initial.daily.completed, false);
  assert.equal(initial.policy.artifactSaveCost, 0);
  assert.equal(initial.missions.filter((mission) => mission.projectId?.startsWith("water-conservation-")).length, 6);
  assert.deepEqual(initial.missions.slice(0, 3).map((mission) => mission.id), ["reading-clue-01", "math-pattern-01", "science-leaf-01"]);
  assert.equal(initial.missions.find((mission) => mission.id === "water-math-middle").source.teacherPublished, false);
  assert.equal(initial.missions.every((mission) => !("answer" in mission)), true);
  probe = new DatabaseSync(join(tempDbDir, "eduai.sqlite"));
  probe.exec("PRAGMA busy_timeout=5000");
  const studentId = initial.subject.id;

  const runInput = { operationId: op(), missionId: "reading-clue-01", phase: "evidence", answer: "B", expectedRevision: 0 };
  await request(taskPath, runInput, 401, "");
  await request(taskPath, runInput, 403, teacher);
  await request(taskPath, runInput, 403, cookie, { origin: "https://invalid.example" });
  await request(taskPath, runInput, 415, cookie, { "content-type": "text/plain" });
  await request(taskPath, { ...runInput, studentId: "other" }, 400);
  const admin = await login("admin", "Admin@123");
  const switched = await fetch(`${base}/api/auth/switch-role`, { method: "POST", headers: { cookie: admin, "content-type": "application/json" }, body: JSON.stringify({ role: "student" }) });
  assert.equal(switched.status, 200);
  const demo = switched.headers.get("set-cookie").split(";", 1)[0];
  await request(taskPath, runInput, 403, demo);
  checks.push("auth, teacher, demo, CSRF, media type and strict input boundaries");

  const run1 = await request(taskPath, runInput);
  assert.equal(run1.taskRun.revision, 1);
  assert.equal((await request(taskPath, runInput)).stateVersion, run1.stateVersion);
  await request(taskPath, { ...runInput, answer: "A" }, 409);
  const stale = await request(taskPath, { ...runInput, operationId: op() }, 409);
  assert.equal(stale.error.authoritative.taskRun.revision, 1);
  assert.equal((await bootstrap()).taskRuns[0].answer, "B");
  const answer = await evidence("reading-clue-01", "B");
  assert.equal((await bootstrap()).daily.completed, false, "one correct answer must not complete the task");
  const acceptedId = answer.evidence.id;
  await request(taskPath, { ...runInput, operationId: op(), phase: "summary", evidenceId: acceptedId, reflection: "跳过步骤", expectedRevision: 1 }, 409);
  const run2 = await request(taskPath, { ...runInput, operationId: op(), phase: "outcome", evidenceId: acceptedId, expectedRevision: 1 });
  const run3 = await request(taskPath, { ...runInput, operationId: op(), phase: "reflection", reflection: "我先找动作幅度，再用原句解释。", evidenceId: acceptedId, expectedRevision: 2 });
  assert.ok(run3.stateVersion > run2.stateVersion);
  const finish = { ...runInput, operationId: op(), phase: "summary", evidenceId: acceptedId, expectedRevision: 3 };
  await request(taskPath, finish, 409);
  const scheduled = await request("/api/v2/manor/reviews", { operationId: op(), evidenceId: acceptedId, strategy: "换一段短文找线索", window: "tomorrow" });
  assert.equal(scheduled.review.title, "寻找春雨的线索");
  assert.equal(scheduled.review.due, false);
  assert.equal("answer" in scheduled.review.question, false);
  probe.exec("CREATE TRIGGER v6_injected_failure BEFORE INSERT ON learning_artifacts BEGIN SELECT RAISE(ABORT,'isolated rollback probe'); END;");
  const failed = await fetch(`${base}${taskPath}`, { method: "POST", headers: { cookie, "content-type": "application/json" }, body: JSON.stringify(finish) });
  assert.equal(failed.status, 500);
  await failed.text();
  probe.exec("DROP TRIGGER v6_injected_failure;");
  const afterRollback = await bootstrap();
  assert.equal(afterRollback.taskRuns[0].revision, 3);
  assert.equal(afterRollback.daily.completed, false);
  await request(`/api/v2/manor/operations/${finish.operationId}`, undefined, 404);
  const finished = await request(taskPath, finish);
  assert.equal(finished.taskRun.phase, "summary");
  assert.ok(finished.taskRun.artifactId);
  assert.ok(finished.taskRun.completedAt);
  assert.equal((await bootstrap()).daily.completed, true);
  const receipt = await request(`/api/v2/manor/operations/${finish.operationId}`);
  assert.equal(receipt.status, "committed");
  assert.deepEqual(receipt.result, finished);
  assert.deepEqual(await request(taskPath, finish), finished);
  await request(`/api/v2/manor/operations/${finish.operationId}`, undefined, 404, other);
  checks.push("task drafts, step validation, reflection artifact, rollback, replay and private operation lookup");

  const reviewPath = `/api/v2/manor/reviews/${scheduled.review.id}/actions`;
  await request(reviewPath, { operationId: op(), action: "complete", answer: "C", expectedRevision: 1 }, 409);
  await request(reviewPath, { operationId: op(), action: "defer", expectedRevision: 1 }, 404, other);
  const deferred = await request(reviewPath, { operationId: op(), action: "defer", expectedRevision: 1 });
  assert.ok(deferred.review.dueAt > scheduled.review.dueAt);
  assert.equal(deferred.review.revision, 2);
  probe.prepare("UPDATE review_schedules SET dueAt=? WHERE id=? AND studentId=?").run(Date.now() - 1000, scheduled.review.id, studentId);
  const beforeReviewEnergy = (await bootstrap()).resources.growthEnergy;
  const wrong = await request(reviewPath, { operationId: op(), action: "complete", answer: "A", expectedRevision: 2 });
  assert.equal(wrong.feedback.correct, false);
  assert.equal(wrong.review.status, "scheduled");
  assert.equal(wrong.review.completedAt, null);
  assert.equal((await bootstrap()).reviews[0].lastAnswer, "A");
  const reviewInput = { operationId: op(), action: "complete", answer: "C", expectedRevision: 3 };
  const done = await request(reviewPath, reviewInput);
  assert.equal(done.review.status, "completed");
  assert.equal(done.feedback.correct, true);
  assert.ok(done.review.completedAt);
  assert.equal((await bootstrap()).resources.growthEnergy, beforeReviewEnergy);
  assert.deepEqual(await request(reviewPath, reviewInput), done);
  assert.equal(probe.prepare("SELECT COUNT(*) AS n FROM manor_review_attempts WHERE reviewId=?").get(scheduled.review.id).n, 2);
  checks.push("future/due review distinction, variation answer, correction, defer, complete, no duplicate reward");

  const artifactInput = { operationId: op(), artifactType: "explanation", title: "我的节水草稿", content: "这是尚未提交老师的节水观察。", visibility: "private" };
  const draft = await request(artifactPath, artifactInput);
  assert.equal(draft.artifact.status, "draft");
  assert.equal(draft.artifact.evidenceId, null);
  assert.deepEqual(draft.consumptions, []);
  const free = await request(artifactPath, { ...artifactInput, operationId: op(), evidenceId: acceptedId, grantAllocations: [{ grantId: "unrelated-grant-never-consumed", amount: 4 }] });
  assert.equal(free.artifact.status, "saved");
  assert.equal(free.resources.growthEnergy, beforeReviewEnergy);
  await request(artifactPath, { ...artifactInput, operationId: op(), evidenceId: acceptedId }, 404, other);
  const pendingPortfolio = await request("/api/portfolio/summary?mode=full");
  assert.equal(pendingPortfolio.manorArtifacts.length, 0, "unreviewed draft leaked to approved portfolio");
  checks.push("free artifact saves with no grants or mismatched legacy grants, owned sources, no fake archive");

  const expressionInput = { operationId: op(), missionId: "water-reading-middle", evidenceType: "expression", content: "模拟数据中覆盖组少用25升水，两组叶片状态相近，还需多周观察。" };
  const expression = await request("/api/v2/manor/evidence", expressionInput);
  const expressionId = expression.evidence.id;
  const decisionPath = `/api/v2/teacher/manor/evidence/${expressionId}/decisions`;
  const feedback = await request(decisionPath, { operationId: op(), status: "revise", expectedRevision: 1, reason: "请说明节水比例的计算基准，并保留模拟数据限制。" }, 200, teacher);
  assert.equal(feedback.evidence.revision, 2);
  const returned = (await bootstrap()).evidence.find((item) => item.id === expressionId);
  assert.match(returned.feedback.reason, /计算基准/);
  assert.equal(returned.submission.content, expressionInput.content);
  const revisedInput = { ...expressionInput, operationId: op(), evidenceId: expressionId, expectedRevision: 2, content: "模拟数据中以常规100升为基准，少用25升即25%；两组叶片状态相近，建议重复多周，不能推断全年。" };
  await request("/api/v2/manor/evidence", { ...revisedInput, expectedRevision: 1 }, 409);
  await request("/api/v2/manor/evidence", revisedInput, 404, other);
  const revised = await request("/api/v2/manor/evidence", revisedInput);
  assert.equal(revised.evidence.id, expressionId);
  assert.equal(revised.evidence.revision, 3);
  assert.equal(revised.evidence.attemptCount, 2);
  assert.equal(revised.evidence.attempts[0].submission.content, expressionInput.content);
  assert.equal(revised.evidence.submission.content, revisedInput.content);
  const beforeApprovalCopy = await request(artifactPath, { ...artifactInput, operationId: op(), evidenceId: expressionId,
    artifactType: "observation", title: "审核之前另写的标题", content: revisedInput.content });
  assert.notEqual(beforeApprovalCopy.artifact.status, "archived");
  await request(decisionPath, { operationId: op(), status: "accepted_mastery", expectedRevision: 2, reason: "旧版本不得覆盖新提交。" }, 409, teacher);
  const queue = await request("/api/v2/teacher/manor/evidence?status=pending_review", undefined, 200, teacher);
  assert.equal(queue.items.find((item) => item.id === expressionId).submission.content, revisedInput.content);
  const approvalInput = { operationId: op(), status: "accepted_mastery", expectedRevision: 3, reason: "计算基准正确，建议与数据和限制一致。" };
  const approved = await request(decisionPath, approvalInput, 200, teacher);
  assert.equal(approved.grant, null, "sample project must not manufacture grants");
  await request("/api/v2/manor/evidence", { ...revisedInput, operationId: op(), expectedRevision: 4 }, 409);
  const portfolio = await request("/api/portfolio/summary?mode=full");
  const archive = portfolio.manorArtifacts.find((item) => item.evidenceId === expressionId);
  assert.equal(archive.status, "archived");
  assert.equal(archive.content, revisedInput.content);
  assert.equal(archive.revision, 2);
  assert.equal(archive.evidenceRevision, 4);
  assert.equal(archive.sourceUrl.startsWith("/student/manor?artifactId="), true);
  const currentArtifact = (await bootstrap()).artifacts.find((item) => item.id === archive.id);
  assert.deepEqual(currentArtifact, archive);
  assert.notEqual((await bootstrap()).artifacts.find((item) => item.id === beforeApprovalCopy.artifact.id).status, "archived");
  const teacherPortfolio = await request(`/api/portfolio/summary?studentId=${studentId}&mode=full`, undefined, 200, teacher);
  assert.deepEqual(teacherPortfolio.manorArtifacts, portfolio.manorArtifacts);
  await request(`/api/portfolio/summary?studentId=${studentId}&mode=full`, undefined, 403, other);
  for (const [index, artifactType] of ["observation", "explanation"].entries()) {
    const unreviewed = await request(artifactPath, { ...artifactInput, operationId: op(), evidenceId: expressionId,
      artifactType, title: `未经审核的新标题${index + 1}`, content: revisedInput.content });
    assert.notEqual(unreviewed.artifact.status, "archived", "matching content must not approve a new artifact title/type");
    assert.equal(unreviewed.artifact.teacherFeedback, null, "source review must not masquerade as approval of this artifact");
  }
  const afterCopies = await request("/api/portfolio/summary?mode=full");
  assert.deepEqual(afterCopies.manorArtifacts.map((item) => item.id), portfolio.manorArtifacts.map((item) => item.id));
  assert.equal(afterCopies.entries.filter((item) => item.evidenceId === expressionId).length, 1);
  // A projection with no teacher decision for its exact revision must fail closed.
  probe.prepare("UPDATE learning_evidence SET revision=revision+1 WHERE id=?").run(expressionId);
  assert.equal((await request("/api/portfolio/summary?mode=full")).manorArtifacts.some((item) => item.id === archive.id), false);
  probe.prepare("UPDATE learning_evidence SET revision=revision-1 WHERE id=?").run(expressionId);
  assert.equal((await request("/api/portfolio/summary?mode=full")).manorArtifacts.find((item) => item.id === archive.id).evidenceRevision, 4);
  checks.push("only canonical expression at the exact reviewed version is archived; copied content cannot forge title/type approval");
  checks.push("expression -> teacher revision -> immutable resubmit -> stale review rejection -> exact portfolio archive");

  const teacherRecord = probe.prepare("SELECT id,classId FROM users WHERE username=?").get("teacher");
  probe.prepare("UPDATE users SET classId=? WHERE id=?").run("v6-revoked-class", teacherRecord.id);
  const revokedReplay = await request(decisionPath, approvalInput, 404, teacher);
  assert.equal(revokedReplay.error.code, "EVIDENCE_NOT_FOUND");
  await request(decisionPath, { ...approvalInput, operationId: op() }, 404, teacher);
  assert.equal(Object.hasOwn(revokedReplay, "evidence"), false);
  probe.prepare("UPDATE users SET classId=? WHERE id=?").run(teacherRecord.classId, teacherRecord.id);
  assert.deepEqual(await request(decisionPath, approvalInput, 200, teacher), approved);
  checks.push("teacher operation replay rechecks current class ownership before returning private evidence");

  const sample = await evidence("water-math-middle", "B");
  assert.equal(sample.evidence.status, "accepted_practice");
  assert.equal(sample.grant, null);
  assert.equal(sample.feedback.reward, 0);
  assert.equal((await bootstrap()).resources.growthEnergy, beforeReviewEnergy);
  const cropState = await bootstrap();
  const lockedCrop = cropState.cropAccess.find((crop) => !crop.unlocked);
  assert.ok(lockedCrop, "fixture needs a locked specialty crop");
  const empty = cropState.plots.find((plot) => plot.unlocked && !plot.cropId);
  const lockedResult = await request(`/api/v2/manor/plots/${empty.id}/actions`, { operationId: op(), action: "plant", cropId: lockedCrop.id, expectedRevision: empty.revision, grantAllocations: [] }, 422);
  assert.equal(lockedResult.error.code, "CROP_LOCKED");
  const planted = await request(`/api/v2/manor/plots/${empty.id}/actions`, { operationId: op(), action: "plant", cropId: "wheat", expectedRevision: empty.revision, grantAllocations: [] });
  const nurtureInput = { operationId: op(), action: "nurture", expectedRevision: planted.plot.revision, grantAllocations: [{ grantId: answer.grant.id, amount: 8 }] };
  const nurtured = await request(`/api/v2/manor/plots/${empty.id}/actions`, nurtureInput);
  assert.equal(nurtured.consumptions[0].amount, 8);
  assert.equal(nurtured.plot.evidenceId, acceptedId);
  assert.deepEqual(await request(`/api/v2/manor/plots/${empty.id}/actions`, nurtureInput), nurtured);
  assert.equal((await bootstrap()).resources.growthEnergy, beforeReviewEnergy - 8);
  const science = await evidence("science-leaf-01", "A");
  const grown = await request(`/api/v2/manor/plots/${empty.id}/actions`, { operationId: op(), action: "nurture", expectedRevision: nurtured.plot.revision,
    grantAllocations: [{ grantId: answer.grant.id, amount: 4 }, { grantId: science.grant.id, amount: 4 }] });
  assert.equal(grown.consumptions.length, 2, "split grants must retain both consumption records");
  const mature = await request(`/api/v2/manor/plots/${empty.id}/actions`, { operationId: op(), action: "nurture", expectedRevision: grown.plot.revision,
    grantAllocations: [{ grantId: science.grant.id, amount: 8 }] });
  assert.equal(mature.plot.status, "ready");
  const beforeHarvest = await bootstrap();
  const harvestInput = { operationId: op(), action: "harvest", expectedRevision: mature.plot.revision, grantAllocations: [] };
  const harvested = await request(`/api/v2/manor/plots/${empty.id}/actions`, harvestInput);
  assert.equal(harvested.harvest.evidenceId, science.evidence.id);
  assert.equal(harvested.plot.cropId, null);
  assert.equal(harvested.plot.evidenceId, null);
  assert.deepEqual(harvested.consumptions, []);
  assert.deepEqual(await request(`/api/v2/manor/plots/${empty.id}/actions`, harvestInput), harvested);
  const afterHarvest = await bootstrap();
  assert.equal(afterHarvest.resources.harvestedTotal, beforeHarvest.resources.harvestedTotal + 1);
  assert.equal(afterHarvest.harvestHistory[0].evidenceId, science.evidence.id);
  assert.equal(afterHarvest.grants.length, beforeHarvest.grants.length);
  assert.equal(afterHarvest.resources.growthEnergy, beforeHarvest.resources.growthEnergy);
  const math = await evidence("math-pattern-01", "B");
  const contribution = await request("/api/v2/manor/class-build/contributions", { operationId: op(), amount: 3, grantAllocations: [{ grantId: math.grant.id, amount: 3 }] });
  assert.equal(contribution.accepted, 3);
  assert.equal(contribution.consumptions[0].purpose, "class_build");
  assert.equal((await bootstrap()).grants.find((grant) => grant.id === math.grant.id).remainingUnits, 7);
  checks.push("sample scope, crop locks, split plot grants, source-preserving harvest without reward and class contribution");

  // Reuse only this task's temporary database to verify a genuine process cold start.
  probe.close(); probe = undefined;
  await server.cleanup(); server = undefined;
  server = await startIsolatedManorDevServer({ label: "manor-v6-restart", tempDbDir });
  base = server.base;
  cookie = await login("student", "Student@123");
  const restored = await bootstrap();
  assert.equal(restored.taskRuns.find((run) => run.id === finished.taskRun.id).reflection, run3.taskRun.reflection);
  assert.equal(restored.artifacts.find((item) => item.id === archive.id).content, revisedInput.content);
  assert.equal(restored.reviews.find((review) => review.id === scheduled.review.id).status, "completed");
  assert.deepEqual((await request(`/api/v2/manor/operations/${finish.operationId}`)).result, finished);
  checks.push("cold restart restores task, reflection, artifact, teacher feedback, review and operation receipt");

  probe = new DatabaseSync(join(tempDbDir, "eduai.sqlite"));
  probe.exec("PRAGMA busy_timeout=5000");
  const restartInput = { operationId: op(), missionId: runInput.missionId, phase: "evidence", expectedRevision: finished.taskRun.revision };
  await request(taskPath, restartInput, 409, cookie);
  const previousDay = Math.floor((Date.now() + 8 * 3_600_000) / 86_400_000) * 86_400_000 - 8 * 3_600_000 - 1;
  probe.prepare("UPDATE manor_task_runs SET completedAt=?,updatedAt=? WHERE id=? AND studentId=?")
    .run(previousDay, previousDay, finished.taskRun.id, studentId);
  const beforeRestart = await bootstrap();
  assert.equal(beforeRestart.daily.completed, false);
  assert.equal(beforeRestart.taskRuns.find((run) => run.id === finished.taskRun.id).phase, "summary", "GET must never restart a completed run");
  await request(taskPath, { ...restartInput, operationId: op(), expectedRevision: finished.taskRun.revision - 1 }, 409);
  probe.exec("CREATE TRIGGER v6_restart_failure BEFORE UPDATE ON manor_task_runs BEGIN SELECT RAISE(ABORT,'isolated restart rollback'); END;");
  const restartFailure = await fetch(`${base}${taskPath}`, { method: "POST", headers: { cookie, "content-type": "application/json" }, body: JSON.stringify(restartInput) });
  assert.equal(restartFailure.status, 500);
  await restartFailure.text();
  probe.exec("DROP TRIGGER v6_restart_failure;");
  const failedRestartState = await bootstrap();
  assert.equal(failedRestartState.taskRunHistory.length, 0);
  assert.equal(failedRestartState.taskRuns[0].id, finished.taskRun.id);
  assert.equal(failedRestartState.stateVersion, beforeRestart.stateVersion);
  const [restarted, concurrentRestart] = await Promise.all([request(taskPath, restartInput), request(taskPath, restartInput)]);
  assert.deepEqual(concurrentRestart, restarted);
  assert.notEqual(restarted.taskRun.id, finished.taskRun.id);
  assert.equal(restarted.taskRun.revision, finished.taskRun.revision + 1, "CAS revision must not reset and permit stale updates");
  assert.equal(restarted.taskRun.phase, "evidence");
  assert.equal(restarted.taskRun.answer, "");
  assert.equal(restarted.taskRun.reflection, "");
  assert.equal(restarted.taskRun.evidenceId, null);
  assert.equal(restarted.taskRun.artifactId, null);
  assert.equal(restarted.taskRun.completedAt, null);
  assert.equal(restarted.archivedTaskRun.id, finished.taskRun.id);
  assert.equal(restarted.archivedTaskRun.reflection, run3.taskRun.reflection);
  assert.deepEqual(await request(taskPath, restartInput), restarted);
  const afterRestart = await bootstrap();
  assert.equal(afterRestart.taskRunHistory.filter((run) => run.id === finished.taskRun.id).length, 1);
  assert.equal(afterRestart.artifacts.some((item) => item.id === finished.taskRun.artifactId), true);
  assert.equal(afterRestart.reviews.find((item) => item.id === scheduled.review.id).status, "completed");
  assert.equal(afterRestart.daily.completed, false);
  assert.throws(() => probe.prepare("UPDATE manor_task_run_history SET archivedAt=0 WHERE id=?").run(finished.taskRun.id), /immutable/);
  assert.throws(() => probe.prepare("DELETE FROM manor_task_run_history WHERE id=?").run(finished.taskRun.id), /immutable/);
  assert.equal(probe.prepare("SELECT COUNT(*) AS n FROM manor_domain_events WHERE studentId=? AND eventType='task_run.restarted'").get(studentId).n, 1);
  assert.deepEqual(await request(taskPath, finish), finished, "previous run operation replays its original receipt");
  assert.equal((await bootstrap()).taskRuns[0].id, restarted.taskRun.id);
  await request(taskPath, { ...restartInput, operationId: op(), expectedRevision: finished.taskRun.revision }, 409);
  const carriedEvidence = await request(taskPath, { ...restartInput, operationId: op(), phase: "outcome", expectedRevision: restarted.taskRun.revision, evidenceId: acceptedId }, 409);
  assert.equal(carriedEvidence.error.code, "TASK_FRESH_EVIDENCE_REQUIRED");
  probe.prepare("UPDATE learning_evidence SET evidenceKey=? WHERE id=?").run(`reading-clue-01:${Math.floor((previousDay + 8 * 3_600_000) / 86_400_000)}`, acceptedId);
  const newDayEvidence = await evidence("reading-clue-01", "B");
  assert.notEqual(newDayEvidence.evidence.id, acceptedId);
  const newOutcome = await request(taskPath, { ...restartInput, operationId: op(), phase: "outcome", expectedRevision: restarted.taskRun.revision, evidenceId: newDayEvidence.evidence.id });
  assert.equal(newOutcome.taskRun.id, restarted.taskRun.id);
  assert.equal(newOutcome.taskRun.reflection, "");
  assert.equal((await bootstrap()).daily.completed, false);
  checks.push("explicit next Beijing day restart preserves immutable prior run, artifacts and reviews without GET writes or revision ABA");
  console.log(JSON.stringify({ ok: true, isolation: "temporary SQLite and separate Next output; no real database", checks }, null, 2));
} finally {
  probe?.close();
  await server?.cleanup();
  const target = resolve(tempDbDir);
  assert.ok(target.startsWith(`${resolve(tmpdir())}${sep}`) && basename(target).startsWith("eduai-manor-v6-"));
  rmSync(target, { recursive: true, force: true, maxRetries: 30, retryDelay: 250 });
}
